### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by grimgarharu** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#11] opened 2020-04-23 04:20 UTC
Whenever I have this installed, the game crashes whenever the game is close to finishing loading when joining a server. Which doesn't happen to my other customs installed. I also tried Ultimate-Tf2-Visual-Fix as the only one in custom but it still crashes. Is it because Valve servers are sv_pure 1?

**Comment by agrastiOs** [comment] 2020-04-23 11:12
Could you drop in your config.cfg?

**Comment by NotTsunami** [comment] 2020-05-03 18:15
Crashes on joining as well. mastercomfig 8.100.0 medium-high with no extra models, disable pyroland, no soundscapes, no tutorial, null-cancelling movement and flat mouse. This has only happened since preview 5, worked fine on preview 4.

**Comment by agrastiOs** [comment] 2020-05-04 20:27
@NotTsunami, that's very interesting. I wonder what could make things crash in preview 5 that wasn't in preview 4.
Can you test out this vpk and see if it crashes for you in the same scenario? https://files.catbox.moe/6aocrq.vpk Also, do you have player outlines on?

**Comment by NotTsunami** [comment] 2020-05-04 20:42
I just realized that I switched from mastercomfig medium preset to
medium-high the same time I upgraded to the latest beta version, which does
enable player outlines. I'll test it tonight (along with other presets)
after I get off from work!

**Comment by NotTsunami** [comment] 2020-05-05 01:10
@agrastiOs I wonder if this requires certain conditions, I tried reproducing yesterday's crash and I could not reproduce it. I have switched back to beta 5 and will let you know if I encounter any more crashes.

**Comment by lza9** [comment] 2020-05-06 21:05
I have the same issue. Using the latest version causes my game to crash when joining a server 90% of the time.

**Comment by agrastiOs** [comment] 2020-05-06 21:39
@lza9 Was the crash issue non-existent on the previous beta?

**Comment by NotTsunami** [comment] 2020-05-07 06:32
Crashed upon joining Viaduct

**Comment by agrastiOs** [comment] 2020-05-07 11:13
@NotTsunami what was the sv_pure value?

**Comment by Raffadiely** [comment] 2020-05-18 17:07
If it's any help, I've been having this issue too.
I'm using mastercomfig Low preset with High textures + decals.
The game works fine for the first server I play on, but then crashes whenever I would change map. I get as far as "Sending client info..." and then the game force-closes without an error message, presumably as it is asked to render the map.
This happens when changing servers while playing, or if the server changes map at the end of a round.
This happens in both Casual and community servers, seemingly regardless of sv_pure setting (tested with Creators.tf, FITH, and Valve Casual, producing the same symptoms).
This seems to happen even with _just_ the Visual Fix applied, and nothing else in my /custom/
Please let me know if there's any more information I could provide that might help, or if there are any tests I could run to troubleshoot.

**Comment by agrastiOs** [comment] 2020-09-22 10:11
@Raffadiely Please try only playing community servers in a session and see if you get crashes then

**Comment by agrastiOs** [comment] 2020-09-22 10:12
Closing pending feedback.

**Closed by agrastiOs** 2020-09-22 10:12 UTC
Labels: help wanted

**Comment by SakiiCode** [comment] 2021-03-24 16:30
I have the same problem as @Raffadiely. I'm on linux and happens with community (FaceIT) servers too.

**Comment by agrastiOs** [comment] 2021-03-28 12:31
@SakiiCode. Faceit 12v12 blocks all custom content for the time being.
