### ISSUE TITLE
Coffin Nail Sniper Rifle (Well-Worn) Texture Bug 

### ISSUE THREAD

**Issue by Dupiter-AU** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#59] opened 2022-01-20 06:41 UTC
After installing UVF, my Coffin Nail Sniper Rifle has a completely buggered scope:

![Screenshot_20220120_163138](https://user-images.githubusercontent.com/82429716/150286679-8d40a6c1-3aaa-4bfd-be44-b2ee147e1002.png)

This does not occur with Stock:

![Screenshot_20220120_163154](https://user-images.githubusercontent.com/82429716/150286715-41d6d810-2b45-4a75-9b0c-469c2bd9d302.png)

**Comment by treacherousfiend** [comment] 2022-01-29 02:08
I believe this is a dupe of #25

**Closed** 2022-01-31 11:59 UTC
Labels: duplicate
