### ISSUE TITLE
Causes TF2 to crash upon joining `sv_pure` servers

### ISSUE THREAD

**Issue by Tkain** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#49] opened 2021-06-21 15:32 UTC
I've been having this issue for a long time where installing the Ultimate TF2 Visual Fix Pack causes the game to crash when joining some servers (most notably, many of the Valve and Skial ones). Interestingly, it only crashes the game sometimes, although if the game crashes on a server when it's first joined, it's likely to keep crashing for a while if you keep trying to rejoin that server. The crashing doesn't occur when the fixes are removed.

I'm currently going through the files in groups to see which ones, if any of them specifically, are causing the crash.

**Comment by Tkain** [comment] 2021-06-22 23:55
Currently troubleshooting to find the offending file now. So far, it's not a material file problem. Will update this post with more information as time goes on.

**Comment by agrastiOs** [comment] 2021-06-26 19:55
Thanks, most likely it is the issue with the sv_pure system being susceptible to crashes on the model side.

**Comment by Tkain** [comment] 2021-06-26 22:20
Yeah, it's almost certainly an `sv_pure` issue, especially seeing as how this has occurred to me on Valve servers as well as Skial ones. I've been able to deduce the offending models as the C-models for the Sniper Rifle (`weapons/c_models/c_sniperrifle`) and the Crusader's Crossbow (`workshop/weapons/c_models/c_crusaders_crossbow`) - after taking those ones out, I haven't had crashes since.

Of course, the most ideal fix would be to get Valve to fix whatever code bug is causing these crashes since they don't occur on non-`sv_pure` servers, but for now, taking those models out should work as a workaround.

**Comment by agrastiOs** [comment] 2021-09-18 13:16
I can **confirm** that the aforementioned workaround works. There are some plans that would allow everyone to do this workaround quick in a future release.

**Comment by Excalibur624** [comment] 2021-12-14 01:34
An update on this situation: It seems c_skullbat_skeleton.vmt is another culprit of the crashing since the Scream Fortress update. I'll update if there's any more I can find

**Comment by agrastiOs** [comment] 2021-12-14 10:06
Huh, are you sure? That is not a model but just a material.

**Comment by Excalibur624** [comment] 2021-12-14 16:17
Yeah, I know that. In the Scream Fortress update Valve updated the materials for the Bat Outta Hell, and the ones from this pack seemed to conflict with it on sv_pure servers. 
I was crashing even after removing the crossbow and sniper rifle C models, and deleting the skullbat material seemed to have fixed it. Unless it was just a freak thing on my end, but I haven't crashed since

**Comment by agrastiOs** [comment] 2022-04-09 22:38
Please see the latest release for a workaround to the problem.

**Comment by agrastiOs** [comment] 2022-04-09 22:40
> Yeah, I know that. In the Scream Fortress update Valve updated the materials for the Bat Outta Hell, and the ones from this pack seemed to conflict with it on sv_pure servers. I was crashing even after removing the crossbow and sniper rifle C models, and deleting the skullbat material seemed to have fixed it. Unless it was just a freak thing on my end, but I haven't crashed since

Can't see that to be the case.

**Comment by agrastiOs** [comment] 2024-07-17 22:11
As this is not a bug in our side, closing.

**Closed by agrastiOs** 2024-07-17 22:11 UTC
Labels: bug
